# Nesse aqruivo vou subir dois containers a API e o DB
version: '3'

services:
  api:
    build: .
    container_name: chat_api
    tty: true
    command: sh
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    container_name: chat_db
    ports:
      - 3306:3306
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: 'always'
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
networks:
  db-network:
    driver: bridge
